name: Generate Lots of Logs 7

on: [push, workflow_dispatch]

jobs:
  generate_logs:
    runs-on: ubuntu-20.04-ppc64le

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate Logs
        run: |
          for i in {1..1000}; do
            echo "Log entry $i"
          done
